var workPattern = {
	"workPattern0": "初始化",
	"workPattern1": "手动",			
	"workPattern2": "半自动",			
	"workPattern3": "全自动"		
};
var connectionPattern = {
		"connectionPattern0": "未连接",
		"connectionPattern1": "已连接",			
	};
var parms = {
		"Mold_Open_P1" : "开模一段压力",
		"Mold_Open_V1" : "开模一段速度",
		"Mold_Open_S1" : "开模一段位置",
		"Mold_Open_P2" : "开模二段压力",
		"Mold_Open_V2" : "开模二段速度",
		"Mold_Open_S2" : "开模二段位置",
		"Mold_Open_P3" : "开模三段压力",
		"Mold_Open_V3" : "开模三段速度",
		"Mold_Open_S3" : "开模三段位置",
		"Mold_Open_P4" : "开模四段压力",
		"Mold_Open_V4" : "开模四段速度",
		"Mold_Open_S4" : "开模四段位置",
		"Mold_Open_P5" : "开模五段压力",
		"Mold_Open_V5" : "开模五段速度",
		"Mold_Open_S5" : "开模五段位置",
		"Mold_Open_P6" : "开模末段压力",
		"Mold_Open_V6" : "开模末段速度",
		"Mold_Open_SE" : "开模末段位置",
		"Mold_Open_Step" : "开模段数",
		"Mold_Close_P1" : "关模一段压力",
		"Mold_Close_V1" : "关模一段速度",
		"Mold_Close_S1" : "关模一段位置",
		"Mold_Close_P2" : "关模二段压力",
		"Mold_Close_V2" : "关模二段速度",
		"Mold_Close_S2" : "关模二段位置",
		"Mold_Close_P3" : "关模三段压力",
		"Mold_Close_V3" : "关模三段速度",
		"Mold_Close_S3" : "关模三段位置",
		"Mold_Close_P4" : "关模四段压力",
		"Mold_Close_V4" : "关模四段速度",
		"Mold_Close_S4" : "关模四段位置",
		"Mold_Close_P5" : "关模五段压力",
		"Mold_Close_V5" : "关模五段速度",
		"Mold_Close_S5" : "关模五段位置",
		"Mold_Close_PE" : "关模末段压力",
		"Mold_Close_VE" : "关模末段速度",
		"Mold_Close_SE" : "关模末段位置",
		"Mold_Close_Step" : "合模段数",
		"Eject_FWD_P1" : "托进一段压力",
		"Eject_FWD_S1" : "托进一段位置",
		"Eject_FWD_V1" : "托进一段速度",
		"Eject_FWD_P2" : "托进二段压力",
		"Eject_FWD_S2" : "托进二段位置",
		"Eject_FWD_V2" : "托进二段速度",
		"Eject_FWD_PE" : "托进末段压力",
		"Eject_FWD_SE" : "托进末段位置",
		"Eject_FWD_VE" : "托进末段速度",
		"Eject_FWD_Step" : "托模前进段数",
		"Eject_BWD_P1" : "托退一段压力",
		"Eject_BWD_S1" : "托退一段位置",
		"Eject_BWD_V1" : "托退一段速度",
		"Eject_BWD_P2" : "托退二段压力",
		"Eject_BWD_S2" : "托退二段位置",
		"Eject_BWD_V2" : "托退二段速度",
		"Eject_BWD_PE" : "托退末段压力",
		"Eject_BWD_SE" : "托退末段位置",
		"Eject_BWD_VE" : "托退末段速度",
		"Eject_BWD_Step" : "托模后退段数",
		"Inject_P1" : "射出一段压力",
		"Inject_V1" : "射出一段速度",
		"Inject_S1" : "射出一段位置",
		"Inject_P2" : "射出二段压力",
		"Inject_V2" : "射出二段速度",
		"Inject_S2" : "射出二段位置",
		"Inject_P3" : "射出三段压力",
		"Inject_V3" : "射出三段速度",
		"Inject_S3" : "射出三段位置",
		"Inject_P4" : "射出四段压力",
		"Inject_V4" : "射出四段速度",
		"Inject_S4" : "射出四段位置",
		"Inject_P5" : "射出五段压力",
		"Inject_V5" : "射出五段速度",
		"Inject_S5" : "射出五段位置",
		"Inject_P6" : "射出六段压力",
		"Inject_V6" : "射出六段速度",
		"Inject_S6" : "射出六段位置",
		"Inject_Step" : "注射段数",
		"Inject_Set_Pressure" : "注射设定压力",
		"Holding_Pressure_1" : "保压第一段压力",
		"Holding_Pressure_2" : "保压第二段压力",
		"Holding_Pressure_3" : "保压第三段压力",
		"Holding_Pressure_4" : "保压第四段压力",
		"Holding_Time_1" : "保压第一段时间",
		"Holding_Time_2" : "保压第二段时间",
		"Holding_Time_3" : "保压第三段时间",
		"Holding_Time_4" : "保压第四段时间",
		"Holding_Step" : "保压段数",
		"Charge_Force_1" : "储料一段压力限制",
		"Charge_Verlocity_1" : "储料一段速度",
		"Charge_Position_1" : "储料一段位置",
		"Charge_Force_2" : "储料二段压力限制",
		"Charge_Verlocity_2" : "储料二段速度",
		"Charge_Position_2" : "储料二段位置",
		"Charge_Force_3" : "储料三段压力限制",
		"Charge_Verlocity_3" : "储料三段速度",
		"Charge_Position_3" : "储料三段位置",
		"Back_Pressure_1" : "储料第一段背压",
		"Back_Pressure_2" : "储料第二段背压",
		"Back_Pressure_3" : "储料第三段背压",
		"Charge_step" : "储料段数",
		"Core_In_Pressure_A" : "中子A进压力",
		"Core_In_Verlocity_A" : "中子A进速度",
		"Core_Selection_A" : "中子A选择开关",
		"Core_In_Mold_Position_A" : "中子A进模板位置",
		"Core_In_Mode_A" : "中子A进模式",
		"Core_In_Delay_Time_A" : "中子A进延迟时间",
		"Core_In_Time_A" : "中子A进时间",
		"Core_In_Standby_A" : "中子A进保持功能选择",
		"Core_Out_Mold_Position_A" : "中子A出模板位置",
		"Core_Out_Mode_A" : "中子A出模式",
		"Core_Out_Delay_Time_A" : "中子A出延迟时间",
		"Core_Out_Time_A" : "中子A出时间",
		"Core_Selection_B" : "中子B选择开关",
		"Core_In_Mold_Position_B" : "中子B进模板位置",
		"Core_In_Mode_B" : "中子B进模式",
		"Core_In_Delay_Time_B" : "中子B进延迟时间",
		"Core_In_Time_B" : "中子B进时间",
		"Core_In_Standby_B" : "中子B进保持功能选择",
		"Core_Out_Mold_Position_B" : "中子B出模板位置",
		"Core_Out_Mode_B" : "中子B出模式",
		"Core_Out_Delay_Time_B" : "中子B出延迟时间",
		"Core_Out_Time_B" : "中子B出时间",
		"Core_Selection_C" : "中子C选择开关",
		"Core_In_Mold_Position_C" : "中子C进模板位置",
		"Core_In_Mode_C" : "中子C进模式",
		"Core_In_Delay_Time_C" : "中子C进延迟时间",
		"Core_In_Time_C" : "中子C进时间",
		"Core_In_Standby_C" : "中子C进保持功能选择",
		"Core_Out_Mold_Position_C" : "中子C出模板位置",
		"Core_Out_Mode_C" : "中子C出模式",
		"Core_Out_Delay_Time_C" : "中子C出延迟时间",
		"Core_Out_Time_C" : "中子C出时间",
		"Injection_Unit_Backward_Time" : "座台后退时间",
		"Injection_Unit_Backward_Delay_Time" : "座台后退延迟时间",
		"Injection_Unit_Forward_Delay_Time" : "座台前进安全时间",
		"Show_SB_Safety" : "射退时间",
		"sSB_Velocity" : "射退速度",
		"sHolding_Speedlimit" : "速度上限"
};
var warningcode = {
		"warningcode1": "产生报警",			
		"warningcode2": "报警已解决"			
};
var subtaskstatus = {
		"status1": "未开始",			
		"status2": "进行中",
		"status4": "待确认",
		"status3": "已完成"
};